# Generated by Django 3.2.20 on 2023-08-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название соц.сети')),
                ('social_url', models.URLField(blank=True, max_length=500)),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='Логотип соц.сети')),
            ],
            options={
                'verbose_name': 'Соц.сеть',
                'verbose_name_plural': 'Соц.сети',
            },
        ),
    ]
